name: CI
on:
  push:
    branches:
      - "main"
      - "master"
      - "versions/*"
    tags:
      - "v*"
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  mkdocs-release:
    # Release documentation on version tag, but ignore pre-releases
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')
    uses: ./.github/workflows/mkdocs.yml
